### ISSUE TITLE
EvilCraft Infuser doesn't keep blood.

### ISSUE THREAD

**Issue by MentalMouse** [gigaherz/PackingTape#18]
When I tried to use the tape on an EvilCraft Infuser with a Tenacity II upgrade:

1) It did keep the upgrade, but...
2)  the upgrade was then stuck in the Infuser (it dropped normally when the Infuser was broken)...
3) and it did _not_ keep the blood contained in the infuser (which is why I was trying this in the first place).

**Comment by gigaherz** [comment]
I see, that is strange. The way the tape works, is that it stores all the TileEntity data in the same way that the block would save to disk when the game saves (as NBT tags), so if this block is losing data, it must be storing the blood by some other means.
I will take a look, but I suspect this will be something I can't fix. If that's the case, then I will have to add a blacklist entry for this block, and possibly other things from this mod, so that the tape refuses to work with them.

**Comment by gigaherz** [comment]
Preliminary investigation seems to indicate that they handle their blocks in some special way, that is incompatible with the vanilla method for placing a block item with NBT tags embedded. The packaged block DOES contain all the data, but it's ignored when unpacking. Since I use a method that uses this vanilla process as-is, and I have no means to run their replacement logic, this seems to be the cause for the TE placing without data.
