### ISSUE TITLE
1.14.4 Pig spawners on unpacking spawners

### ISSUE THREAD

**Issue by MrKashew** [gigaherz/PackingTape#23]
and the pig spawners dont seem to work? D:

**Comment by gigaherz** [comment]
I'll check. As you may understand, since they are blacklisted by default, testing if spawners work isn't exactly high priority for me. :P

**Comment by gigaherz** [comment]
Actually, the issue was that Minecraft has a restriction that doesn't allow placing mob spawners with NBT data, which my mod was enforcing.

I changed things in v0.9, so that whitelisting a TE will ignore this restriction.
Note however, the configuration format has changed, the TE whitelist/blacklist now uses registry names instead of class names.

**Comment by Bricktricker** [comment]
It looks like this bug reappeared in 1.19.2:

When unpacking a spawner in survival a pig-spawner appears,
but when you unpack the spawner in creative the correct spawner gets placed.

Forge: 1.19.2-43.1.33
PackingTape: 1.19-0.14.0

**Comment by gigaherz** [comment]
Thanks for the report. No need to do anything now, but next time it would be best to create a new issue referencing this one by number (writing #number with the id of the issue).
