### ISSUE TITLE
Triple Chests

### ISSUE THREAD

**Issue by RheyvenFox** [gigaherz/PackingTape#4]
You can place a vanilla single chest next to another Double Vanilla chest. This then creates a buggy triple slotted chest. As cool as this is, I believe it can corrupt your world. I know it's a known Vanilla MC bug with the triple chest thing. 

http://puu.sh/tLe2e/bde6fe3388.png

**Comment by gigaherz** [comment]
I know. I did as much testing as I could trying to find a way in which this could cause data loss or corruption, and so far as I can tell, it can't happen. This is because each individual chest takes care of its own 27 slots, and they are only combined when interacting with them.

It does concern me to leave this "issue" unresolved, but it would be rather complex to figure out of the block WANTS to be placed there, since there's no direct way of asking. Because the goal of the mod was to make it as simple as possible, I chose to keep this... "feature" in place. I just don't recommend making use of it since it could possibly have unwanted side-effects when interacting with the GUI or hoppers.

**Comment by RheyvenFox** [comment]
Awesome! They might have fixed the corruption thing then on vanilla side, or that was just a myth, and it's a moot point then. And if it's not an issue it's a fun bug and makes for an interesting "feature" for sure. Thanks for letting me know!

**Comment by gigaherz** [comment]
I have just released 0.7.0 for mc 1.12, which includes logic to fix the triple-chest thing. I don't know that it's a perfect fix, but it will do.
